// <copyright file="BaseModel.cs" company="HazeLabs">
// Copyright (c) HazeLabs. All rights reserved.
// </copyright>

namespace SistemaMirno.Model
{
    /// <summary>
    /// A class that represents the basic data model.
    /// </summary>
    public abstract class BaseModel
    {
        /// <summary>
        /// Gets or sets the Id of the model (which is autogenerated in the database).
        /// </summary>
        public int Id { get; set; }
    }
}