// <copyright file="BaseModel.cs" company="HazeLabs">
// Copyright (c) HazeLabs. All rights reserved.
// </copyright>

using System.ComponentModel.DataAnnotations;

namespace SistemaMirno.Model
{
    /// <summary>
    /// A class that represents the basic data model.
    /// </summary>
    public class ModelBase
    {
        /// <summary>
        /// Gets or sets the Id of the model (which is autogenerated in the database).
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the timestamp property used for concurrency checking.
        /// </summary>
        [Timestamp]
        public byte[] Timestamp { get; set; }
    }
}