// <copyright file="ModelBase.cs" company="HazeLabs">
// Copyright (c) HazeLabs. All rights reserved.
// </copyright>

using System.ComponentModel.DataAnnotations;

namespace SistemaMirno.Model
{
    /// <summary>
    /// Represents a base entity model.
    /// </summary>
    public class ModelBase
    {
        /// <summary>
        /// Gets or sets the id of the entity (which is autogenerated in the database).
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the timestamp of the last modification, used for concurrency checking.
        /// </summary>
        [Timestamp]
        public byte[] Timestamp { get; set; }
    }
}