// <auto-generated />
namespace SistemaMirno.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RequisitionsSalesClients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequisitionsSalesClients));
        
        string IMigrationMetadata.Id
        {
            get { return "202008181332514_Requisitions-Sales-Clients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
