// <copyright file="Configuration.cs" company="HazeLabs">
// Copyright (c) HazeLabs. All rights reserved.
// </copyright>
// <auto-generated />

using System.Data.Entity.Migrations;

namespace SistemaMirno.DataAccess.Migrations
{
    internal sealed class Configuration : DbMigrationsConfiguration<SistemaMirno.DataAccess.MirnoDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
        }

        protected override void Seed(SistemaMirno.DataAccess.MirnoDbContext context)
        {
        }
    }
}